msgbox "cest un message lol"
msgbox "bon ba bye"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
msgbox "je rigole hihihiha"
